stages:
  - coverage
  - builddocs
  - publishdocs

variables:
  LC_ALL: C.UTF-8
  LANG: "en_US.UTF-8"
  JEKYLL_ENV: production

coverage:
  image: cirrusci/flutter
  stage: coverage
  coverage: '/^\s+lines.+: (\d+.\d*%)/'
  dependencies: []
  script:
    - sudo apt-get update -qq && sudo apt-get install -qq apt-transport-https curl gnupg lcov git
    - ./scripts/test.sh
    - ./scripts/coverage.sh
    - flutter pub pub publish --dry-run

builddocs:
  stage: builddocs
  image: cirrusci/flutter
  script:
    - dartdoc
  artifacts:
    paths:
      - doc/api/
  only:
  - master

publishdocs:
  stage: publishdocs
  image: ruby:2.3
  script:
    - bundle install
    - bundle exec jekyll build -d public
  dependencies:
    - builddocs
  artifacts:
    paths:
    - public
  only:
  - master