image: cirrusci/flutter

stages:
- coverage

variables:
  LC_ALL: "en_US.UTF-8"
  LANG: "en_US.UTF-8"

coverage:
  stage: coverage
  coverage: '/^\s+lines.+: (\d+.\d*%)/'
  dependencies: []
  script:
  - sudo apt-get update -qq && sudo apt-get install -qq apt-transport-https curl gnupg lcov git
  - ./scripts/test.sh
  - ./scripts/coverage.sh
  - flutter pub pub publish --dry-run