image: cirrusci/flutter

stages:
  - coverage
  - docs

variables:
  LC_ALL: "en_US.UTF-8"
  LANG: "en_US.UTF-8"

coverage:
  image: cirrusci/flutter
  stage: coverage
  coverage: '/^\s+lines.+: (\d+.\d*%)/'
  dependencies: []
  script:
    - sudo apt-get update -qq && sudo apt-get install -qq apt-transport-https curl gnupg lcov git
    - ./scripts/test.sh
    - ./scripts/coverage.sh
    - flutter pub pub publish --dry-run

docs:
  stage: docs
  scripts:
  - image: cirrusci/flutter
    script:
    - dartdoc
  - image: ruby:2.3
    script:
    - cd docs/api/ && bundle exec jekyll build -d test
    - cd docs/api/ && bundle exec jekyll build -d public
  only:
  - master